#!/bin/bash
docker build -t appsync-lambda . --platform=linux/amd64 
docker tag appsync-lambda:latest <aws account id>.dkr.ecr.<aws region>.amazonaws.com/appsync-lambda:latest
docker push <aws account id>.dkr.ecr.<aws region>.amazonaws.com/appsync-lambda:latest 
