#!/bin/bash
docker build -t appsync-driver-partner . --platform=linux/amd64 
docker tag appsync-driver-partner:latest <aws account id>.dkr.ecr.<aws region>.amazonaws.com/appsync-driver-partner:latest
docker push <aws account id>.dkr.ecr.<aws region>.amazonaws.com/appsync-driver-partner:latest
